### ISSUE TITLE
Lista 1 AOD Grafy ?????????????

### ISSUE THREAD

**Issue by MrKubul** [Grubre/Studia-WPPT#1]
Chujowo zrobione zadne zadanie nie dziala co to kurwa jest. Siedze na labach 7 30 i mam ochote sie zajebac

**Comment by Grubre** [comment]
Can you please provide more details or steps to reproduce the issue?

**Comment by MrKubul** [comment]
> Can you please provide more details or steps to reproduce the issue?

To by nic nie dalo i tak...

**Comment by Grubre** [comment]
![avatarguystaring.jpg](https://user-images.githubusercontent.com/69735117/235667224-5cd6562a-6632-4e30-be42-0d08920043b1.jpg)

**Comment by MrKubul** [comment]
Bylo, zamykam
